openapi: 3.0.1
info:
  title: Postavki FBW
  version: ordersfbw
  description: |
    <div class="description_important">  
        Uznat bolhe o postavkah FBW mohno v <a href="https://seller.wildberries.ru/instructions/subcategory/5a8e1202-0865-45b7-acae-5d0afc7add56?goBackOption=prevRoute&categoryId=479385c6-de01-4b4d-ad4e-ed941e65582e">spravohnom centre</a>
    </div>

    Upravlenie informaciei dla formirovania postavok, skladskimi dannymi i statusami
  x-file-name: orders-fbw
security:
  - HeaderApiKey: []
tags:
  - name: Postavki
    description: ''
paths:
  /api/v1/acceptance/coefficients:
    servers:
      - url: https://supplies-api.wildberries.ru
    get:
      security:
        - HeaderApiKey: []
      tags:
        - Postavki
      summary: Koefficienty priemki
      description: |
        Vozvrahaet koefficienty priemki dla konkretnyh skladov na blihaihie 14 dnei <div class="description_important">Priemka dla postavki dostupna tolko pri sohetanii: <br>  `coefficient` — `0` ili `1` <br>  i <br>  `allowUnload` — `true`</div>
        <div class="description_limit">  
          Maksimum 6 zaprosov v <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">minutu</a> na odin akkaunt prodavca
        </div>
      parameters:
        - name: warehouseIDs
          in: query
          description: ID skladov.<br>Po umolhaniu vozvrahautsa dannye po vsem skladam
          schema:
            type: string
          example: 507,117501
      responses:
        '200':
          description: Uspehno
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.AcceptanceCoefficient'
              examples:
                ResponseCoefficients:
                  $ref: '#/components/examples/ResponseCoefficients'
        '400':
          description: Nepravilnyi zapros
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorModel'
              examples:
                BadWarehouseIDsParamOld:
                  $ref: '#/components/examples/Response400CoefficientsOld'
                BadWarehouseIDsParamNew:
                  $ref: '#/components/examples/Response400CoefficientsNew'
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: Dostup zaprehen
        '404':
          description: Ne naideno
        '429':
          $ref: '#/components/responses/429'
  /api/v1/acceptance/options:
    servers:
      - url: https://supplies-api.wildberries.ru
    post:
      security:
        - HeaderApiKey: []
      tags:
        - Postavki
      summary: Opcii priemki
      description: |
        Vozvrahaet informaciu o tom, kakie sklady i tipy upakovki dostupny dla postavki. Spisok skladov opredelaetsa po barkodu tovara i ego kolihestvu
        <div class="description_limit">  
          Maksimum 30 zaprosov v <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">minutu</a> na odin akkaunt prodavca
        </div>
      parameters:
        - name: warehouseID
          in: query
          description: ID sklada. <br> Esli parametr ne ukazan, vozvrahautsa dannye po vsem skladam.<br> <b>Maksimum odno znahenie</b>
          schema:
            type: string
          example: 507
      requestBody:
        content:
          application/json:
            schema:
              type: array
              maxItems: 5000
              items:
                $ref: '#/components/schemas/models.Good'
            examples:
              RequestOptions:
                $ref: '#/components/examples/RequestOptions'
        required: true
      responses:
        '200':
          description: Uspehno
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.OptionsResultModel'
              examples:
                Response:
                  $ref: '#/components/examples/OptionsResponse'
        '400':
          description: Nekorrektnyi zapros
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/models.ErrorModel'
              examples:
                BadWarehouseIDsParam:
                  $ref: '#/components/examples/Response400Options'
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: Dostup zaprehen
        '404':
          description: Ne naideno
        '429':
          $ref: '#/components/responses/429'
      x-codegen-request-body-name: goods
  /api/v1/warehouses:
    servers:
      - url: https://supplies-api.wildberries.ru
    get:
      security:
        - HeaderApiKey: []
      tags:
        - Postavki
      summary: Spisok skladov
      description: |
        Vozvrahaet spisok skladov WB
        <div class="description_limit">  
          Maksimum 6 zaprosov v <a href="/openapi/api-information#tag/Vvedenie/Limity-zaprosov">minutu</a> na odin akkaunt prodavca
        </div>
      responses:
        '200':
          description: Uspehno
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.WarehousesResultItems'
        '401':
          $ref: '#/components/responses/401'
        '403':
          description: Dostup zaprehen
        '404':
          description: Ne naideno
        '429':
          $ref: '#/components/responses/429'
components:
  securitySchemes:
    HeaderApiKey:
      type: apiKey
      name: Authorization
      in: header
  schemas:
    models.AcceptanceCoefficient:
      type: object
      properties:
        date:
          type: string
          description: Data nahala deistvia koefficienta
        coefficient:
          type: number
          description: |
            Koefficient priemki:
              - `-1` — priemka nedostupna, vne zavisimosti ot znahenia pola `allowUnload`
              - `0` — besplatnaa priemka
              - ot `1` — mnohitel stoimosti priemki
        warehouseID:
          type: integer
          description: ID sklada. Po nemu mohno poluhit [informaciu o sklade](https://dev.wildberries.ru/openapi/orders-fbw#tag/Postavki/paths/~1api~1v1~1warehouses/get)
        warehouseName:
          type: string
          description: Nazvanie sklada
        allowUnload:
          type: boolean
          description: |
            Dostupnost priemki dla postavok dannogo tipa, smotri znahenie pola `boxTypeName`:
             - `true` — priemka dostupna
             - `false` — priemka ne dostupna 
        boxTypeName:
          type: string
          description: |
            Tip postavki:
              - `Koroba`
              - `Monopallety`
              - `Superseif`
              - `QR-postavka s korobami`
        boxTypeID:
          type: integer
          description: |
            ID tipa postavki:
              - `2` — Koroba
              - `5` — Monopallety
              - `6` — Superseif
            <br>Dla tipa postavki **QR-postavka s korobami** pole ne vozvrahaetsa
        storageCoef:
          type: string
          nullable: true
          description: Koefficient hranenia
        deliveryCoef:
          type: string
          nullable: true
          description: Koefficient logistiki
        deliveryBaseLiter:
          type: string
          nullable: true
          description: Stoimost logistiki pervogo litra
        deliveryAdditionalLiter:
          type: string
          nullable: true
          description: Stoimost logistiki kahdogo sleduuhego litra
        storageBaseLiter:
          type: string
          nullable: true
          description: |
            Stoimost hranenia:  <br>   <b>Dla pallet</b> - stoimost za odnu palletu   <br>  <b>Dla korobov</b> - stoimost hranenia za pervyi litr
        storageAdditionalLiter:
          type: string
          nullable: true
          description: |
            Stoimost hranenia kahdogo posleduuhego litra:   <br>  <b>Dla pallet</b> - vsegda budet <code>null</code>, t.k. stoimost hranenia za edinicu pallety opredelaetsa v <code>StorageBaseLiter</code>   <br>  <b>Dla korobov</b> - stoimost hranenia za kahdyi posleduuhii litr
        isSortingCenter:
          type: boolean
          description: |
            Tip sklada:
             - `true` — sortirovohnyi centr (Sc)
             - `false` — obyhnyi 
    models.WarehousesResultItems:
      type: object
      properties:
        ID:
          type: integer
          description: ID sklada
        name:
          type: string
          description: Nazvanie sklada
        address:
          type: string
          description: Adres sklada
        workTime:
          type: string
          description: Rehim raboty sklada
        acceptsQr:
          type: boolean
          description: |
            Prinimaet li sklad QR-postavki:
            - `true` — da
            - `false` — net
      example:
        ID: 210515
        name: Vehki
        address: Lipkinskoe hosse, 2-i kilometr, vl1s1, poselok Vehki, gorodskoi okrug Mytihi, Moskovskaa oblast
        workTime: 24/7
        acceptsQR: false
    models.Good:
      type: object
      properties:
        quantity:
          type: integer
          description: |
            Summarnoe kolihestvo tovarov, planiruemyh dla postavki. <br>  <b>Maksimum 999999</b>
          minimum: 1
          maximum: 999999
        barcode:
          type: string
          description: Barkod iz kartohki tovara
    models.ErrorModel:
      type: object
      properties:
        status:
          type: integer
          description: HTTP status-kod
        title:
          type: string
          description: ID ohibki
        detail:
          type: string
          description: Opisanie ohibki
        requestId:
          type: string
          description: ID zaprosa
        origin:
          type: string
          description: Servis, vernuvhii ohibku
    models.OptionsResultModel:
      type: object
      properties:
        result:
          type: array
          items:
            type: object
            properties:
              barcode:
                type: string
                description: Barkod iz kartohki tovara
              error:
                type: object
                description: Dannye ohibki. Pri nalihii
                properties:
                  title:
                    type: string
                    description: ID ohibki
                  detail:
                    type: string
                    description: Opisanie ohibki
              isError:
                type: boolean
                description: |
                  Nalihie ohibki:
                    - `true` — ohibka est
                    - Pola net — ohibka otsutstvuet   
              warehouses:
                type: array
                nullable: true
                description: Spisok skladov. Pri nalihii ohibki budet `null`
                items:
                  type: object
                  properties:
                    warehouseID:
                      type: integer
                      description: ID sklada. Po nemu mohno poluhit [informaciu o sklade](./orders-fbw#tag/Postavki/paths/~1api~1v1~1warehouses/get)
                    canBox:
                      type: boolean
                      description: |
                        Tip upakovki **Korob**:
                          - `true` — dostupen
                          - `false` — nedostupen
                    canMonopallet:
                      type: boolean
                      description: |
                        Tip upakovki **Monopalleta**:
                          - `true` — dostupen
                          - `false` — nedostupen
                    canSupersafe:
                      type: boolean
                      description: |
                        Tip upakovki **Superseif**:
                          - `true` — dostupen
                          - `false` — nedostupen
        requestId:
          type: string
          description: ID zaprosa pri nalihii ohibok
  examples:
    RequestOptions:
      value:
        - quantity: 1
          barcode: k
        - quantity: 7
          barcode: '1111111111'
    ResponseCoefficients:
      value:
        - date: '2024-04-11T00:00:00Z'
          coefficient: -1
          warehouseID: 217081
          warehouseName: Sc Bransk 2
          allowUnload: false
          boxTypeName: Superseif
          boxTypeID: 6
          storageCoef: null
          deliveryCoef: null
          deliveryBaseLiter: null
          deliveryAdditionalLiter: null
          storageBaseLiter: null
          storageAdditionalLiter: null
          isSortingCenter: true
    Response400CoefficientsOld:
      value:
        status: 400
        title: bad request
        detail: warehouseIDs param is incorrect
        requestId: a6bdc2a4d2fde51c2036fa8af2483886
        origin: supply-api
      description: <b>Deprecated</b> <br>  Znahenie parametra `warehouseIDs` nekorrektno
    Response400CoefficientsNew:
      value:
        status: 400
        title: bad request
        detail: Nevernyi format warehouseIDs
        requestId: a6bdc2a4d2fde51c2036fa8af2483886
        origin: supply-api
      description: Znahenie parametra `warehouseIDs` ne ukazano, ili nekorrektno
    OptionsResponse:
      value:
        result:
          - barcode: krrr
            warehouses: null
            error:
              title: barcode validation error
              detail: barcode krrr is not found
            isError: true
          - barcode: '123456789'
            warehouses:
              - warehouseID: 205349
                canBox: true
                canMonopallet: false
                canSupersafe: false
              - warehouseID: 211622
                canBox: false
                canMonopallet: true
                canSupersafe: false
              - warehouseID: 214951
                canBox: true
                canMonopallet: false
                canSupersafe: false
              - warehouseID: 206319
                canBox: true
                canMonopallet: false
                canSupersafe: false
        requestId: kr53d2bRKYmkK2N6zaNKHs
    Response400Options:
      value:
        status: 400
        title: bad request
        detail: Nevernyi format warehouseID
        requestId: a6bdc2a4d2fde51c2036fa8af2483886
        origin: supply-api
      description: Znahenie parametra `warehouseID` ne ukazano, ili nekorrektno
  responses:
    '401':
      description: Polzovatel ne avtorizovan
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Zagolovok ohibki
              detail:
                type: string
                description: Detali ohibki
              code:
                type: string
                description: Vnutrennii kod ohibki
              requestId:
                type: string
                description: Unikalnyi ID zaprosa
              origin:
                type: string
                description: ID vnutrennego servisa WB
              status:
                type: number
                description: HTTP status-kod
              statusText:
                type: string
                description: Rashifrovka HTTP status-koda
              timestamp:
                type: string
                format: RFC3339
                description: Data i vrema zaprosa
          example:
            title: unauthorized
            detail: 'token problem; token is malformed: could not base64 decode signature: illegal base64 data at input byte 84'
            code: 07e4668e--a53a3d31f8b0-[UK-oWaVDUqNrKG]; 03bce=277; 84bd353bf-75
            requestId: 7b80742415072fe8b6b7f7761f1d1211
            origin: s2s-api-auth-catalog
            status: 401
            statusText: Unauthorized
            timestamp: '2024-09-30T06:52:38Z'
    '429':
      description: Slihkom mnogo zaprosov
      content:
        application/json:
          schema:
            type: object
            properties:
              title:
                type: string
                description: Zagolovok ohibki
              detail:
                type: string
                description: Detali ohibki
              code:
                type: string
                description: Vnutrennii kod ohibki
              requestId:
                type: string
                description: Unikalnyi ID zaprosa
              origin:
                type: string
                description: ID vnutrennego servisa WB
              status:
                type: number
                description: HTTP status-kod
              statusText:
                type: string
                description: Rashifrovka HTTP status-koda
              timestamp:
                type: string
                format: RFC3339
                description: Data i vrema zaprosa
          example:
            title: too many requests
            detail: limited by c122a060-a7fb-4bb4-abb0-32fd4e18d489
            code: 07e4668e-ac2242c5c8c5-[UK-4dx7JUdskGZ]
            requestId: 9d3c02cc698f8b041c661a7c28bed293
            origin: s2s-api-auth-catalog
            status: 429
            statusText: Too Many Requests
            timestamp: '2024-09-30T06:52:38Z'
